
/**************************************************************
 *	
 *	cheat, 8 bit, 44100Hz,
 *	1 channel, 42624 bytes/channel
 *	Total Size: 1 * 42624 + 4 (header) = 42668 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\cheat.wav
 *	Time-stamp: Sun Nov 30 22:49:14 2014
 *	
 **************************************************************/

#ifndef __CHEATH__
#define __CHEATH__

#define CHEATFREQ 44100
#define CHEATLEN 42624

extern const unsigned char cheat[42624];

#endif /* __CHEATH__ */
