
/**************************************************************
 *	
 *	endlevel, 8 bit, 44100Hz,
 *	1 channel, 66152 bytes/channel
 *	Total Size: 1 * 66152 + 4 (header) = 66196 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\endlevel.wav
 *	Time-stamp: Sat Nov 29 23:56:15 2014
 *	
 **************************************************************/

#ifndef __ENDLEVELH__
#define __ENDLEVELH__

#define ENDLEVELFREQ 44100
#define ENDLEVELLEN 66152

extern const unsigned char endlevel[66152];

#endif /* __ENDLEVELH__ */
