
/**************************************************************
 *	
 *	finishSong, 8 bit, 44100Hz,
 *	1 channel, 1431841 bytes/channel
 *	Total Size: 1 * 1431841 + 4 (header) = 1431885 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\finishSong.wav
 *	Time-stamp: Sun Nov 30 23:43:48 2014
 *	
 **************************************************************/

#ifndef __FINISHSONGH__
#define __FINISHSONGH__

#define FINISHSONGFREQ 44100
#define FINISHSONGLEN 1431841

extern const unsigned char finishSong[1431841];

#endif /* __FINISHSONGH__ */
