
/**************************************************************
 *	
 *	flutter, 8 bit, 44100Hz,
 *	1 channel, 24948 bytes/channel
 *	Total Size: 1 * 24948 + 4 (header) = 24992 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\flutter.wav
 *	Time-stamp: Mon Nov 10 11:35:17 2014
 *	
 **************************************************************/

#ifndef __FLUTTERH__
#define __FLUTTERH__

#define FLUTTERFREQ 44100
#define FLUTTERLEN 24948

extern const unsigned char flutter[24948];

#endif /* __FLUTTERH__ */
