
/**************************************************************
 *	
 *	gameSong_2, 8 bit, 44100Hz,
 *	1 channel, 4730496 bytes/channel
 *	Total Size: 1 * 4730496 + 4 (header) = 4730540 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\gameSong_2.wav
 *	Time-stamp: Sat Nov 29 22:39:40 2014
 *	
 **************************************************************/

#ifndef __GAMESONG_2H__
#define __GAMESONG_2H__

#define GAMESONG_2FREQ 44100
#define GAMESONG_2LEN 4730496

extern const unsigned char gameSong_2[4730496];

#endif /* __GAMESONG_2H__ */
