
/**************************************************************
 *	
 *	gameSong, 8 bit, 48000Hz,
 *	1 channel, 3037440 bytes/channel
 *	Total Size: 1 * 3037440 + 4 (header) = 3037484 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\gameSong.wav
 *	Time-stamp: Sat Nov 29 23:24:00 2014
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 48000
#define GAMESONGLEN 3037440

extern const unsigned char gameSong[3037440];

#endif /* __GAMESONGH__ */
