
/**************************************************************
 *	
 *	jump, 8 bit, 11025Hz,
 *	1 channel, 1733 bytes/channel
 *	Total Size: 1 * 1733 + 4 (header) = 1777 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\jump.wav
 *	Time-stamp: Mon Nov 24 17:25:53 2014
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 1733

extern const unsigned char jump[1733];

#endif /* __JUMPH__ */
