
/**************************************************************
 *	
 *	pickup, 8 bit, 11025Hz,
 *	1 channel, 4207 bytes/channel
 *	Total Size: 1 * 4207 + 4 (header) = 4251 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\pickup.wav
 *	Time-stamp: Tue Nov 25 22:24:10 2014
 *	
 **************************************************************/

#ifndef __PICKUPH__
#define __PICKUPH__

#define PICKUPFREQ 11025
#define PICKUPLEN 4207

extern const unsigned char pickup[4207];

#endif /* __PICKUPH__ */
