
/**************************************************************
 *	
 *	select, 8 bit, 44100Hz,
 *	1 channel, 15132 bytes/channel
 *	Total Size: 1 * 15132 + 4 (header) = 15176 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\select.wav
 *	Time-stamp: Sun Nov 09 11:00:33 2014
 *	
 **************************************************************/

#ifndef __SELECTH__
#define __SELECTH__

#define SELECTFREQ 44100
#define SELECTLEN 15132

extern const unsigned char select[15132];

#endif /* __SELECTH__ */
