
/**************************************************************
 *	
 *	splashSong, 8 bit, 44100Hz,
 *	1 channel, 4556160 bytes/channel
 *	Total Size: 1 * 4556160 + 4 (header) = 4556204 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\splashSong.wav
 *	Time-stamp: Sun Nov 30 23:53:44 2014
 *	
 **************************************************************/

#ifndef __SPLASHSONGH__
#define __SPLASHSONGH__

#define SPLASHSONGFREQ 44100
#define SPLASHSONGLEN 4556160

extern const unsigned char splashSong[4556160];

#endif /* __SPLASHSONGH__ */
