
/**************************************************************
 *	
 *	whoosh, 8 bit, 24000Hz,
 *	1 channel, 23040 bytes/channel
 *	Total Size: 1 * 23040 + 4 (header) = 23084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Nayomi\Dropbox\Documents\School\Fall 2014\CS 2261\Your Game\P04\whoosh.wav
 *	Time-stamp: Sun Nov 30 00:18:28 2014
 *	
 **************************************************************/

#ifndef __WHOOSHH__
#define __WHOOSHH__

#define WHOOSHFREQ 24000
#define WHOOSHLEN 23040

extern const unsigned char whoosh[23040];

#endif /* __WHOOSHH__ */
